//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="eloadsg", ConfigurationName="ServiceReference1.ClientAPIServiceSoap")]
    public interface ClientAPIServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="eloadsg/RequestInput", ReplyAction="*")]
        ECommerce.ServiceReference1.RequestInputResponse RequestInput(ECommerce.ServiceReference1.RequestInputRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="eloadsg/RequestInput", ReplyAction="*")]
        System.Threading.Tasks.Task<ECommerce.ServiceReference1.RequestInputResponse> RequestInputAsync(ECommerce.ServiceReference1.RequestInputRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="eloadsg/RequestAliPayPin", ReplyAction="*")]
        ECommerce.ServiceReference1.RequestAliPayPinResponse RequestAliPayPin(ECommerce.ServiceReference1.RequestAliPayPinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="eloadsg/RequestAliPayPin", ReplyAction="*")]
        System.Threading.Tasks.Task<ECommerce.ServiceReference1.RequestAliPayPinResponse> RequestAliPayPinAsync(ECommerce.ServiceReference1.RequestAliPayPinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="eloadsg/CheckBalance", ReplyAction="*")]
        ECommerce.ServiceReference1.CheckBalanceResponse CheckBalance(ECommerce.ServiceReference1.CheckBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="eloadsg/CheckBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<ECommerce.ServiceReference1.CheckBalanceResponse> CheckBalanceAsync(ECommerce.ServiceReference1.CheckBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="eloadsg/CheckTransactionStatus", ReplyAction="*")]
        ECommerce.ServiceReference1.CheckTransactionStatusResponse CheckTransactionStatus(ECommerce.ServiceReference1.CheckTransactionStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="eloadsg/CheckTransactionStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<ECommerce.ServiceReference1.CheckTransactionStatusResponse> CheckTransactionStatusAsync(ECommerce.ServiceReference1.CheckTransactionStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="eloadsg/SendSMS", ReplyAction="*")]
        ECommerce.ServiceReference1.SendSMSResponse SendSMS(ECommerce.ServiceReference1.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="eloadsg/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<ECommerce.ServiceReference1.SendSMSResponse> SendSMSAsync(ECommerce.ServiceReference1.SendSMSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestInputRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestInput", Namespace="eloadsg", Order=0)]
        public ECommerce.ServiceReference1.RequestInputRequestBody Body;
        
        public RequestInputRequest() {
        }
        
        public RequestInputRequest(ECommerce.ServiceReference1.RequestInputRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="eloadsg")]
    public partial class RequestInputRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sClientUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sClientPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sClientTxID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sProductID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal dProductPrice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sCustomerMobileNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sResponseID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string sResponseStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string sNewBalance;
        
        public RequestInputRequestBody() {
        }
        
        public RequestInputRequestBody(string sClientUserName, string sClientPassword, string sClientTxID, string sProductID, decimal dProductPrice, string sCustomerMobileNumber, string sResponseID, string sResponseStatus, string sNewBalance) {
            this.sClientUserName = sClientUserName;
            this.sClientPassword = sClientPassword;
            this.sClientTxID = sClientTxID;
            this.sProductID = sProductID;
            this.dProductPrice = dProductPrice;
            this.sCustomerMobileNumber = sCustomerMobileNumber;
            this.sResponseID = sResponseID;
            this.sResponseStatus = sResponseStatus;
            this.sNewBalance = sNewBalance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestInputResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestInputResponse", Namespace="eloadsg", Order=0)]
        public ECommerce.ServiceReference1.RequestInputResponseBody Body;
        
        public RequestInputResponse() {
        }
        
        public RequestInputResponse(ECommerce.ServiceReference1.RequestInputResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="eloadsg")]
    public partial class RequestInputResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RequestInputResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sResponseID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sResponseStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sNewBalance;
        
        public RequestInputResponseBody() {
        }
        
        public RequestInputResponseBody(bool RequestInputResult, string sResponseID, string sResponseStatus, string sNewBalance) {
            this.RequestInputResult = RequestInputResult;
            this.sResponseID = sResponseID;
            this.sResponseStatus = sResponseStatus;
            this.sNewBalance = sNewBalance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestAliPayPinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestAliPayPin", Namespace="eloadsg", Order=0)]
        public ECommerce.ServiceReference1.RequestAliPayPinRequestBody Body;
        
        public RequestAliPayPinRequest() {
        }
        
        public RequestAliPayPinRequest(ECommerce.ServiceReference1.RequestAliPayPinRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="eloadsg")]
    public partial class RequestAliPayPinRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sClientUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sClientPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sClientTxID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal dProductPrice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sResponseID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sResponseStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sCardSerial;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string sCardPIN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string sCardExpiry;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string sCardValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string sNewBalance;
        
        public RequestAliPayPinRequestBody() {
        }
        
        public RequestAliPayPinRequestBody(string sClientUserName, string sClientPassword, string sClientTxID, decimal dProductPrice, string sResponseID, string sResponseStatus, string sCardSerial, string sCardPIN, string sCardExpiry, string sCardValue, string sNewBalance) {
            this.sClientUserName = sClientUserName;
            this.sClientPassword = sClientPassword;
            this.sClientTxID = sClientTxID;
            this.dProductPrice = dProductPrice;
            this.sResponseID = sResponseID;
            this.sResponseStatus = sResponseStatus;
            this.sCardSerial = sCardSerial;
            this.sCardPIN = sCardPIN;
            this.sCardExpiry = sCardExpiry;
            this.sCardValue = sCardValue;
            this.sNewBalance = sNewBalance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestAliPayPinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestAliPayPinResponse", Namespace="eloadsg", Order=0)]
        public ECommerce.ServiceReference1.RequestAliPayPinResponseBody Body;
        
        public RequestAliPayPinResponse() {
        }
        
        public RequestAliPayPinResponse(ECommerce.ServiceReference1.RequestAliPayPinResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="eloadsg")]
    public partial class RequestAliPayPinResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RequestAliPayPinResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sResponseID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sResponseStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sCardSerial;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sCardPIN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sCardExpiry;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sCardValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string sNewBalance;
        
        public RequestAliPayPinResponseBody() {
        }
        
        public RequestAliPayPinResponseBody(bool RequestAliPayPinResult, string sResponseID, string sResponseStatus, string sCardSerial, string sCardPIN, string sCardExpiry, string sCardValue, string sNewBalance) {
            this.RequestAliPayPinResult = RequestAliPayPinResult;
            this.sResponseID = sResponseID;
            this.sResponseStatus = sResponseStatus;
            this.sCardSerial = sCardSerial;
            this.sCardPIN = sCardPIN;
            this.sCardExpiry = sCardExpiry;
            this.sCardValue = sCardValue;
            this.sNewBalance = sNewBalance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckBalance", Namespace="eloadsg", Order=0)]
        public ECommerce.ServiceReference1.CheckBalanceRequestBody Body;
        
        public CheckBalanceRequest() {
        }
        
        public CheckBalanceRequest(ECommerce.ServiceReference1.CheckBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="eloadsg")]
    public partial class CheckBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sClientUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sClientPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal dBalance;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sResponseID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sResponseStatus;
        
        public CheckBalanceRequestBody() {
        }
        
        public CheckBalanceRequestBody(string sClientUserName, string sClientPassword, decimal dBalance, string sResponseID, string sResponseStatus) {
            this.sClientUserName = sClientUserName;
            this.sClientPassword = sClientPassword;
            this.dBalance = dBalance;
            this.sResponseID = sResponseID;
            this.sResponseStatus = sResponseStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckBalanceResponse", Namespace="eloadsg", Order=0)]
        public ECommerce.ServiceReference1.CheckBalanceResponseBody Body;
        
        public CheckBalanceResponse() {
        }
        
        public CheckBalanceResponse(ECommerce.ServiceReference1.CheckBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="eloadsg")]
    public partial class CheckBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckBalanceResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal dBalance;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sResponseID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sResponseStatus;
        
        public CheckBalanceResponseBody() {
        }
        
        public CheckBalanceResponseBody(bool CheckBalanceResult, decimal dBalance, string sResponseID, string sResponseStatus) {
            this.CheckBalanceResult = CheckBalanceResult;
            this.dBalance = dBalance;
            this.sResponseID = sResponseID;
            this.sResponseStatus = sResponseStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckTransactionStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckTransactionStatus", Namespace="eloadsg", Order=0)]
        public ECommerce.ServiceReference1.CheckTransactionStatusRequestBody Body;
        
        public CheckTransactionStatusRequest() {
        }
        
        public CheckTransactionStatusRequest(ECommerce.ServiceReference1.CheckTransactionStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="eloadsg")]
    public partial class CheckTransactionStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sClientUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sClientPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sClientTxID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sTransactionStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sTransactionErrorCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sMTMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sResponseID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string sResponseStatus;
        
        public CheckTransactionStatusRequestBody() {
        }
        
        public CheckTransactionStatusRequestBody(string sClientUserName, string sClientPassword, string sClientTxID, string sTransactionStatus, string sTransactionErrorCode, string sMTMsg, string sResponseID, string sResponseStatus) {
            this.sClientUserName = sClientUserName;
            this.sClientPassword = sClientPassword;
            this.sClientTxID = sClientTxID;
            this.sTransactionStatus = sTransactionStatus;
            this.sTransactionErrorCode = sTransactionErrorCode;
            this.sMTMsg = sMTMsg;
            this.sResponseID = sResponseID;
            this.sResponseStatus = sResponseStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckTransactionStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckTransactionStatusResponse", Namespace="eloadsg", Order=0)]
        public ECommerce.ServiceReference1.CheckTransactionStatusResponseBody Body;
        
        public CheckTransactionStatusResponse() {
        }
        
        public CheckTransactionStatusResponse(ECommerce.ServiceReference1.CheckTransactionStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="eloadsg")]
    public partial class CheckTransactionStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckTransactionStatusResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sTransactionStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sTransactionErrorCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sMTMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sResponseID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sResponseStatus;
        
        public CheckTransactionStatusResponseBody() {
        }
        
        public CheckTransactionStatusResponseBody(bool CheckTransactionStatusResult, string sTransactionStatus, string sTransactionErrorCode, string sMTMsg, string sResponseID, string sResponseStatus) {
            this.CheckTransactionStatusResult = CheckTransactionStatusResult;
            this.sTransactionStatus = sTransactionStatus;
            this.sTransactionErrorCode = sTransactionErrorCode;
            this.sMTMsg = sMTMsg;
            this.sResponseID = sResponseID;
            this.sResponseStatus = sResponseStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="eloadsg", Order=0)]
        public ECommerce.ServiceReference1.SendSMSRequestBody Body;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(ECommerce.ServiceReference1.SendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="eloadsg")]
    public partial class SendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sClientUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sClientPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sRecieverMSISDN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sMessageOut;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal dNewBalance;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sResponseID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sResponseStatus;
        
        public SendSMSRequestBody() {
        }
        
        public SendSMSRequestBody(string sClientUserName, string sClientPassword, string sRecieverMSISDN, string sMessageOut, decimal dNewBalance, string sResponseID, string sResponseStatus) {
            this.sClientUserName = sClientUserName;
            this.sClientPassword = sClientPassword;
            this.sRecieverMSISDN = sRecieverMSISDN;
            this.sMessageOut = sMessageOut;
            this.dNewBalance = dNewBalance;
            this.sResponseID = sResponseID;
            this.sResponseStatus = sResponseStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="eloadsg", Order=0)]
        public ECommerce.ServiceReference1.SendSMSResponseBody Body;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(ECommerce.ServiceReference1.SendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="eloadsg")]
    public partial class SendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendSMSResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal dNewBalance;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sResponseID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sResponseStatus;
        
        public SendSMSResponseBody() {
        }
        
        public SendSMSResponseBody(bool SendSMSResult, decimal dNewBalance, string sResponseID, string sResponseStatus) {
            this.SendSMSResult = SendSMSResult;
            this.dNewBalance = dNewBalance;
            this.sResponseID = sResponseID;
            this.sResponseStatus = sResponseStatus;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientAPIServiceSoapChannel : ECommerce.ServiceReference1.ClientAPIServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientAPIServiceSoapClient : System.ServiceModel.ClientBase<ECommerce.ServiceReference1.ClientAPIServiceSoap>, ECommerce.ServiceReference1.ClientAPIServiceSoap {
        
        public ClientAPIServiceSoapClient() {
        }
        
        public ClientAPIServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientAPIServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientAPIServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientAPIServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECommerce.ServiceReference1.RequestInputResponse ECommerce.ServiceReference1.ClientAPIServiceSoap.RequestInput(ECommerce.ServiceReference1.RequestInputRequest request) {
            return base.Channel.RequestInput(request);
        }
        
        public bool RequestInput(string sClientUserName, string sClientPassword, string sClientTxID, string sProductID, decimal dProductPrice, string sCustomerMobileNumber, ref string sResponseID, ref string sResponseStatus, ref string sNewBalance) {
            ECommerce.ServiceReference1.RequestInputRequest inValue = new ECommerce.ServiceReference1.RequestInputRequest();
            inValue.Body = new ECommerce.ServiceReference1.RequestInputRequestBody();
            inValue.Body.sClientUserName = sClientUserName;
            inValue.Body.sClientPassword = sClientPassword;
            inValue.Body.sClientTxID = sClientTxID;
            inValue.Body.sProductID = sProductID;
            inValue.Body.dProductPrice = dProductPrice;
            inValue.Body.sCustomerMobileNumber = sCustomerMobileNumber;
            inValue.Body.sResponseID = sResponseID;
            inValue.Body.sResponseStatus = sResponseStatus;
            inValue.Body.sNewBalance = sNewBalance;
            ECommerce.ServiceReference1.RequestInputResponse retVal = ((ECommerce.ServiceReference1.ClientAPIServiceSoap)(this)).RequestInput(inValue);
            sResponseID = retVal.Body.sResponseID;
            sResponseStatus = retVal.Body.sResponseStatus;
            sNewBalance = retVal.Body.sNewBalance;
            return retVal.Body.RequestInputResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECommerce.ServiceReference1.RequestInputResponse> ECommerce.ServiceReference1.ClientAPIServiceSoap.RequestInputAsync(ECommerce.ServiceReference1.RequestInputRequest request) {
            return base.Channel.RequestInputAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECommerce.ServiceReference1.RequestInputResponse> RequestInputAsync(string sClientUserName, string sClientPassword, string sClientTxID, string sProductID, decimal dProductPrice, string sCustomerMobileNumber, string sResponseID, string sResponseStatus, string sNewBalance) {
            ECommerce.ServiceReference1.RequestInputRequest inValue = new ECommerce.ServiceReference1.RequestInputRequest();
            inValue.Body = new ECommerce.ServiceReference1.RequestInputRequestBody();
            inValue.Body.sClientUserName = sClientUserName;
            inValue.Body.sClientPassword = sClientPassword;
            inValue.Body.sClientTxID = sClientTxID;
            inValue.Body.sProductID = sProductID;
            inValue.Body.dProductPrice = dProductPrice;
            inValue.Body.sCustomerMobileNumber = sCustomerMobileNumber;
            inValue.Body.sResponseID = sResponseID;
            inValue.Body.sResponseStatus = sResponseStatus;
            inValue.Body.sNewBalance = sNewBalance;
            return ((ECommerce.ServiceReference1.ClientAPIServiceSoap)(this)).RequestInputAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECommerce.ServiceReference1.RequestAliPayPinResponse ECommerce.ServiceReference1.ClientAPIServiceSoap.RequestAliPayPin(ECommerce.ServiceReference1.RequestAliPayPinRequest request) {
            return base.Channel.RequestAliPayPin(request);
        }
        
        public bool RequestAliPayPin(string sClientUserName, string sClientPassword, string sClientTxID, decimal dProductPrice, ref string sResponseID, ref string sResponseStatus, ref string sCardSerial, ref string sCardPIN, ref string sCardExpiry, ref string sCardValue, ref string sNewBalance) {
            ECommerce.ServiceReference1.RequestAliPayPinRequest inValue = new ECommerce.ServiceReference1.RequestAliPayPinRequest();
            inValue.Body = new ECommerce.ServiceReference1.RequestAliPayPinRequestBody();
            inValue.Body.sClientUserName = sClientUserName;
            inValue.Body.sClientPassword = sClientPassword;
            inValue.Body.sClientTxID = sClientTxID;
            inValue.Body.dProductPrice = dProductPrice;
            inValue.Body.sResponseID = sResponseID;
            inValue.Body.sResponseStatus = sResponseStatus;
            inValue.Body.sCardSerial = sCardSerial;
            inValue.Body.sCardPIN = sCardPIN;
            inValue.Body.sCardExpiry = sCardExpiry;
            inValue.Body.sCardValue = sCardValue;
            inValue.Body.sNewBalance = sNewBalance;
            ECommerce.ServiceReference1.RequestAliPayPinResponse retVal = ((ECommerce.ServiceReference1.ClientAPIServiceSoap)(this)).RequestAliPayPin(inValue);
            sResponseID = retVal.Body.sResponseID;
            sResponseStatus = retVal.Body.sResponseStatus;
            sCardSerial = retVal.Body.sCardSerial;
            sCardPIN = retVal.Body.sCardPIN;
            sCardExpiry = retVal.Body.sCardExpiry;
            sCardValue = retVal.Body.sCardValue;
            sNewBalance = retVal.Body.sNewBalance;
            return retVal.Body.RequestAliPayPinResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECommerce.ServiceReference1.RequestAliPayPinResponse> ECommerce.ServiceReference1.ClientAPIServiceSoap.RequestAliPayPinAsync(ECommerce.ServiceReference1.RequestAliPayPinRequest request) {
            return base.Channel.RequestAliPayPinAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECommerce.ServiceReference1.RequestAliPayPinResponse> RequestAliPayPinAsync(string sClientUserName, string sClientPassword, string sClientTxID, decimal dProductPrice, string sResponseID, string sResponseStatus, string sCardSerial, string sCardPIN, string sCardExpiry, string sCardValue, string sNewBalance) {
            ECommerce.ServiceReference1.RequestAliPayPinRequest inValue = new ECommerce.ServiceReference1.RequestAliPayPinRequest();
            inValue.Body = new ECommerce.ServiceReference1.RequestAliPayPinRequestBody();
            inValue.Body.sClientUserName = sClientUserName;
            inValue.Body.sClientPassword = sClientPassword;
            inValue.Body.sClientTxID = sClientTxID;
            inValue.Body.dProductPrice = dProductPrice;
            inValue.Body.sResponseID = sResponseID;
            inValue.Body.sResponseStatus = sResponseStatus;
            inValue.Body.sCardSerial = sCardSerial;
            inValue.Body.sCardPIN = sCardPIN;
            inValue.Body.sCardExpiry = sCardExpiry;
            inValue.Body.sCardValue = sCardValue;
            inValue.Body.sNewBalance = sNewBalance;
            return ((ECommerce.ServiceReference1.ClientAPIServiceSoap)(this)).RequestAliPayPinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECommerce.ServiceReference1.CheckBalanceResponse ECommerce.ServiceReference1.ClientAPIServiceSoap.CheckBalance(ECommerce.ServiceReference1.CheckBalanceRequest request) {
            return base.Channel.CheckBalance(request);
        }
        
        public bool CheckBalance(string sClientUserName, string sClientPassword, ref decimal dBalance, ref string sResponseID, ref string sResponseStatus) {
            ECommerce.ServiceReference1.CheckBalanceRequest inValue = new ECommerce.ServiceReference1.CheckBalanceRequest();
            inValue.Body = new ECommerce.ServiceReference1.CheckBalanceRequestBody();
            inValue.Body.sClientUserName = sClientUserName;
            inValue.Body.sClientPassword = sClientPassword;
            inValue.Body.dBalance = dBalance;
            inValue.Body.sResponseID = sResponseID;
            inValue.Body.sResponseStatus = sResponseStatus;
            ECommerce.ServiceReference1.CheckBalanceResponse retVal = ((ECommerce.ServiceReference1.ClientAPIServiceSoap)(this)).CheckBalance(inValue);
            dBalance = retVal.Body.dBalance;
            sResponseID = retVal.Body.sResponseID;
            sResponseStatus = retVal.Body.sResponseStatus;
            return retVal.Body.CheckBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECommerce.ServiceReference1.CheckBalanceResponse> ECommerce.ServiceReference1.ClientAPIServiceSoap.CheckBalanceAsync(ECommerce.ServiceReference1.CheckBalanceRequest request) {
            return base.Channel.CheckBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECommerce.ServiceReference1.CheckBalanceResponse> CheckBalanceAsync(string sClientUserName, string sClientPassword, decimal dBalance, string sResponseID, string sResponseStatus) {
            ECommerce.ServiceReference1.CheckBalanceRequest inValue = new ECommerce.ServiceReference1.CheckBalanceRequest();
            inValue.Body = new ECommerce.ServiceReference1.CheckBalanceRequestBody();
            inValue.Body.sClientUserName = sClientUserName;
            inValue.Body.sClientPassword = sClientPassword;
            inValue.Body.dBalance = dBalance;
            inValue.Body.sResponseID = sResponseID;
            inValue.Body.sResponseStatus = sResponseStatus;
            return ((ECommerce.ServiceReference1.ClientAPIServiceSoap)(this)).CheckBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECommerce.ServiceReference1.CheckTransactionStatusResponse ECommerce.ServiceReference1.ClientAPIServiceSoap.CheckTransactionStatus(ECommerce.ServiceReference1.CheckTransactionStatusRequest request) {
            return base.Channel.CheckTransactionStatus(request);
        }
        
        public bool CheckTransactionStatus(string sClientUserName, string sClientPassword, string sClientTxID, ref string sTransactionStatus, ref string sTransactionErrorCode, ref string sMTMsg, ref string sResponseID, ref string sResponseStatus) {
            ECommerce.ServiceReference1.CheckTransactionStatusRequest inValue = new ECommerce.ServiceReference1.CheckTransactionStatusRequest();
            inValue.Body = new ECommerce.ServiceReference1.CheckTransactionStatusRequestBody();
            inValue.Body.sClientUserName = sClientUserName;
            inValue.Body.sClientPassword = sClientPassword;
            inValue.Body.sClientTxID = sClientTxID;
            inValue.Body.sTransactionStatus = sTransactionStatus;
            inValue.Body.sTransactionErrorCode = sTransactionErrorCode;
            inValue.Body.sMTMsg = sMTMsg;
            inValue.Body.sResponseID = sResponseID;
            inValue.Body.sResponseStatus = sResponseStatus;
            ECommerce.ServiceReference1.CheckTransactionStatusResponse retVal = ((ECommerce.ServiceReference1.ClientAPIServiceSoap)(this)).CheckTransactionStatus(inValue);
            sTransactionStatus = retVal.Body.sTransactionStatus;
            sTransactionErrorCode = retVal.Body.sTransactionErrorCode;
            sMTMsg = retVal.Body.sMTMsg;
            sResponseID = retVal.Body.sResponseID;
            sResponseStatus = retVal.Body.sResponseStatus;
            return retVal.Body.CheckTransactionStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECommerce.ServiceReference1.CheckTransactionStatusResponse> ECommerce.ServiceReference1.ClientAPIServiceSoap.CheckTransactionStatusAsync(ECommerce.ServiceReference1.CheckTransactionStatusRequest request) {
            return base.Channel.CheckTransactionStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECommerce.ServiceReference1.CheckTransactionStatusResponse> CheckTransactionStatusAsync(string sClientUserName, string sClientPassword, string sClientTxID, string sTransactionStatus, string sTransactionErrorCode, string sMTMsg, string sResponseID, string sResponseStatus) {
            ECommerce.ServiceReference1.CheckTransactionStatusRequest inValue = new ECommerce.ServiceReference1.CheckTransactionStatusRequest();
            inValue.Body = new ECommerce.ServiceReference1.CheckTransactionStatusRequestBody();
            inValue.Body.sClientUserName = sClientUserName;
            inValue.Body.sClientPassword = sClientPassword;
            inValue.Body.sClientTxID = sClientTxID;
            inValue.Body.sTransactionStatus = sTransactionStatus;
            inValue.Body.sTransactionErrorCode = sTransactionErrorCode;
            inValue.Body.sMTMsg = sMTMsg;
            inValue.Body.sResponseID = sResponseID;
            inValue.Body.sResponseStatus = sResponseStatus;
            return ((ECommerce.ServiceReference1.ClientAPIServiceSoap)(this)).CheckTransactionStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECommerce.ServiceReference1.SendSMSResponse ECommerce.ServiceReference1.ClientAPIServiceSoap.SendSMS(ECommerce.ServiceReference1.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public bool SendSMS(string sClientUserName, string sClientPassword, string sRecieverMSISDN, string sMessageOut, ref decimal dNewBalance, ref string sResponseID, ref string sResponseStatus) {
            ECommerce.ServiceReference1.SendSMSRequest inValue = new ECommerce.ServiceReference1.SendSMSRequest();
            inValue.Body = new ECommerce.ServiceReference1.SendSMSRequestBody();
            inValue.Body.sClientUserName = sClientUserName;
            inValue.Body.sClientPassword = sClientPassword;
            inValue.Body.sRecieverMSISDN = sRecieverMSISDN;
            inValue.Body.sMessageOut = sMessageOut;
            inValue.Body.dNewBalance = dNewBalance;
            inValue.Body.sResponseID = sResponseID;
            inValue.Body.sResponseStatus = sResponseStatus;
            ECommerce.ServiceReference1.SendSMSResponse retVal = ((ECommerce.ServiceReference1.ClientAPIServiceSoap)(this)).SendSMS(inValue);
            dNewBalance = retVal.Body.dNewBalance;
            sResponseID = retVal.Body.sResponseID;
            sResponseStatus = retVal.Body.sResponseStatus;
            return retVal.Body.SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECommerce.ServiceReference1.SendSMSResponse> ECommerce.ServiceReference1.ClientAPIServiceSoap.SendSMSAsync(ECommerce.ServiceReference1.SendSMSRequest request) {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECommerce.ServiceReference1.SendSMSResponse> SendSMSAsync(string sClientUserName, string sClientPassword, string sRecieverMSISDN, string sMessageOut, decimal dNewBalance, string sResponseID, string sResponseStatus) {
            ECommerce.ServiceReference1.SendSMSRequest inValue = new ECommerce.ServiceReference1.SendSMSRequest();
            inValue.Body = new ECommerce.ServiceReference1.SendSMSRequestBody();
            inValue.Body.sClientUserName = sClientUserName;
            inValue.Body.sClientPassword = sClientPassword;
            inValue.Body.sRecieverMSISDN = sRecieverMSISDN;
            inValue.Body.sMessageOut = sMessageOut;
            inValue.Body.dNewBalance = dNewBalance;
            inValue.Body.sResponseID = sResponseID;
            inValue.Body.sResponseStatus = sResponseStatus;
            return ((ECommerce.ServiceReference1.ClientAPIServiceSoap)(this)).SendSMSAsync(inValue);
        }
    }
}
