//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EloadEntities : DbContext
    {
        public EloadEntities()
            : base("name=EloadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TB_User> TB_User { get; set; }
        public DbSet<TB_Operator> TB_Operator { get; set; }
        public DbSet<TB_Transaction> TB_Transaction { get; set; }
        public DbSet<EWallet> EWallets { get; set; }
        public DbSet<TB_Paypal> TB_Paypal { get; set; }
        public DbSet<TB_Product> TB_Product { get; set; }
    
        public virtual ObjectResult<GetProductByOpId_Result> GetProductByOpId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductByOpId_Result>("GetProductByOpId", idParameter);
        }
    
        public virtual ObjectResult<GetProductByOpId1_Result> GetProductByOpId1(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductByOpId1_Result>("GetProductByOpId1", idParameter);
        }
    }
}
