//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EWallet
    {
        public EWallet()
        {
            this.TB_Paypal = new HashSet<TB_Paypal>();
        }
    
        public int EWalletID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Active { get; set; }
    
        public virtual TB_User TB_User { get; set; }
        public virtual ICollection<TB_Paypal> TB_Paypal { get; set; }
    }
}
