//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Product
    {
        public int TB_ProductID { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> Product_Price { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> OperatorId { get; set; }
        public string IsActive { get; set; }
    
        public virtual TB_Operator TB_Operator { get; set; }
    }
}
