//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Paypal
    {
        public int PaypalId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Type { get; set; }
        public Nullable<int> EWalletID { get; set; }
    
        public virtual EWallet EWallet { get; set; }
    }
}
