//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Transaction
    {
        public int TransactionId { get; set; }
        public string TransactionNumber { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Status { get; set; }
        public string Denomination { get; set; }
        public string ResponseId { get; set; }
        public string Phone { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual TB_User TB_User { get; set; }
    }
}
